# Generated by Django 6.0.1 on 2026-04-01 15:03

import apps.products.models.product
import base.for_model
import django.core.validators
import django.db.models.deletion
import mptt.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='SpecificationName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.IntegerField(default=100, verbose_name='Position')),
                ('unit_measurement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Единица измерения')),
                ('filter_hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Название спецификации',
                'verbose_name_plural': 'Название спецификаций',
                'db_table': 'specification_name',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('position', base.for_model.PositionField(default=0, verbose_name='Позиция')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Изображение')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Доступное для продажи', verbose_name='Количество')),
                ('price', base.for_model.PriceField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('old_price', base.for_model.PriceField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Старая цена')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to=apps.products.models.product.get_upload_path, verbose_name='Изображение')),
                ('position', base.for_model.PositionField(default=0, verbose_name='Позиция')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображение товаров',
                'db_table': 'product_image',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='SpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('value', models.CharField(max_length=255, verbose_name='Название')),
                ('specification_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.specificationname', verbose_name='Название спецификации')),
            ],
            options={
                'verbose_name': 'Значение спецификации',
                'verbose_name_plural': 'Значение спецификаций',
                'db_table': 'specification_value',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specification', to='products.product', verbose_name='Товар')),
                ('specification_name', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='products_specification', to='products.specificationname', verbose_name='Название спецификации')),
                ('specification_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specification', to='products.specificationvalue', verbose_name='Значение спецификаций')),
            ],
            options={
                'verbose_name': 'Спецификация товара',
                'verbose_name_plural': 'Спецификации товара',
                'db_table': 'product_specification',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(related_name='products', through='products.ProductSpecification', to='products.specificationvalue'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_name_d601b7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tree_id', 'lft'], name='products_category_tree_id_0983'),
        ),
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.UniqueConstraint(fields=('product', 'specification_name'), name='unique_product_specification_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_c4c985_idx'),
        ),
    ]
