# Generated by Django 6.0.1 on 2026-04-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationname',
            name='filter_hide',
            field=models.BooleanField(default=False, verbose_name='Не показывать в фильтрах'),
        ),
        migrations.AlterField(
            model_name='specificationname',
            name='position',
            field=models.IntegerField(default=100, verbose_name='Позиция'),
        ),
    ]
