# Generated by Django 6.0.1 on 2026-04-04 15:15

import base.for_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_specificationname_filter_hide_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображение товаров'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='position',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_groups', to='products.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productgroup'),
        ),
        migrations.CreateModel(
            name='ProductImageThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('position', base.for_model.PositionField(default=0, verbose_name='Позиция')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_through', to='products.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_through', to='products.product')),
            ],
            options={
                'verbose_name': 'Изображение товара [позиция]',
                'verbose_name_plural': 'Изображение товаров [позиция]',
                'db_table': 'product_image_through',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='productimage',
            name='products',
            field=models.ManyToManyField(related_name='images', through='products.ProductImageThrough', to='products.product'),
        ),
    ]
