# Generated by Django 6.0.1 on 2026-04-04 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'verbose_name': 'Группа товаров', 'verbose_name_plural': 'Группы товаров'},
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productgroup', verbose_name='Группа товаров'),
        ),
    ]
