# Generated by Django 5.0 on 2026-01-12 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_specificationname_specificationvalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificationname',
            options={'verbose_name': 'Название спецификации', 'verbose_name_plural': 'Название спецификаций'},
        ),
        migrations.AlterModelOptions(
            name='specificationvalue',
            options={'verbose_name': 'Значение спецификации', 'verbose_name_plural': 'Значение спецификаций'},
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='specification_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='products.specificationname', verbose_name='Название спецификации'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='specification_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='products.specificationvalue', verbose_name='Значение спецификаций'),
        ),
        migrations.AlterModelTable(
            name='specificationname',
            table='specification_name',
        ),
        migrations.AlterModelTable(
            name='specificationvalue',
            table='specification_value',
        ),
    ]
