# Generated by Django 6.0.1 on 2026-05-20 14:26

from django.db import migrations, models


def deduplicate_specification_values(apps, schema_editor):
    SpecificationValue = apps.get_model('products', 'SpecificationValue')

    seen = set()
    for spec in SpecificationValue.objects.order_by('id'):
        if spec.value in seen:
            spec.delete()
        else:
            seen.add(spec.value)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productgroup_options_alter_product_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificationvalue',
            options={'ordering': ('specification_name',), 'verbose_name': 'Значение спецификации', 'verbose_name_plural': 'Значение спецификаций'},
        ),
        migrations.AddField(
            model_name='specificationname',
            name='product_name_display',
            field=models.BooleanField(default=False, verbose_name='Показывать в имени товара'),
        ),
        migrations.RunPython(deduplicate_specification_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='specificationvalue',
            name='value',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
