# Generated by Django 5.0 on 2026-01-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_specificationname_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificationvalue',
            old_name='name',
            new_name='value',
        ),
        migrations.AddField(
            model_name='specificationvalue',
            name='specification_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.specificationname', verbose_name='Название спецификации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='specification_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.specificationname', verbose_name='Название спецификации'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='specification_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specification', to='products.specificationvalue', verbose_name='Значение спецификаций'),
        ),
    ]
