# Generated by Django 6.0.1 on 2026-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_specificationvalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
    ]
