# Generated by Django 5.0 on 2026-01-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_name_specificationvalue_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'verbose_name': 'Cпецификация', 'verbose_name_plural': 'Спецификации'},
        ),
        migrations.AlterModelTable(
            name='productspecification',
            table='product_specification',
        ),
    ]
