# Generated by Django 5.0 on 2026-01-12 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productspecification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'verbose_name': 'Спецификация товара', 'verbose_name_plural': 'Спецификации товара'},
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(related_name='products', through='products.ProductSpecification', to='products.specificationvalue'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specification', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='specification_name',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='products_specification', to='products.specificationname', verbose_name='Название спецификации'),
        ),
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.UniqueConstraint(fields=('product', 'specification_name'), name='unique_product_specification_name'),
        ),
    ]
