# Generated by Django 6.0.1 on 2026-01-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_brand_options_rename_qty_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcategory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='historicalspecificationname',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalspecificationvalue',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalspecificationvalue',
            name='specification_name',
        ),
        migrations.DeleteModel(
            name='HistoricalBrand',
        ),
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
        migrations.DeleteModel(
            name='HistoricalSpecificationName',
        ),
        migrations.DeleteModel(
            name='HistoricalSpecificationValue',
        ),
    ]
