# Generated by Django 6.0.1 on 2026-01-13 12:08

from django.db import migrations, models

def set_slug(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')
    Brand = apps.get_model('products', 'Brand')

    for category in Category.objects.all():
        category.save()
    for product in Product.objects.all():
        product.save()
    for brand in Brand.objects.all():
        brand.save()



class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_historicalcategory_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.RunPython(set_slug),
    ]
