# Generated by Django 6.0.1 on 2026-01-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_brand_slug_category_image_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
