# Generated by Django 6.0.1 on 2026-01-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductimage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproductimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalproductspecification',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproductspecification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalproductspecification',
            name='specification_name',
        ),
        migrations.RemoveField(
            model_name='historicalproductspecification',
            name='specification_value',
        ),
        migrations.AddField(
            model_name='specificationname',
            name='filter_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalProductImage',
        ),
        migrations.DeleteModel(
            name='HistoricalProductSpecification',
        ),
    ]
