# Generated by Django 6.0.1 on 2026-04-01 15:03

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import base.for_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Самовывоз"),
                            ("courier", "Курьер"),
                            ("nova_posta", "Nova Posta"),
                        ],
                        default="pickup",
                        max_length=100,
                        verbose_name="Способ доставки",
                    ),
                ),
                (
                    "post_office",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер почтового отделения | почтомата"
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
                (
                    "delivery_cost",
                    base.for_model.PriceField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Стоимость доставки",
                    ),
                ),
                ("is_delivered", models.BooleanField(default=False, verbose_name="Доставлено")),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Время доставки"
                    ),
                ),
                (
                    "returned",
                    models.CharField(
                        blank=True,
                        choices=[("full", "Полный"), ("partial", "Частичный")],
                        editable=False,
                        max_length=100,
                        null=True,
                        verbose_name="Возврат",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="address.address",
                        verbose_name="Адрес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставка",
                "verbose_name_plural": "Доставки",
                "db_table": "delivery",
            },
        ),
    ]
