# Generated by Django 5.0 on 2025-12-09 22:27

import base.for_model
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьер'), ('nova_posta', 'Nova Posta')], default='pickup', max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('quickly', 'Срочно'), ('standard', 'Стандартно')], default='standard', max_length=100)),
                ('possible_delivery_time_from', models.DateTimeField(blank=True, help_text='Желаемое время доставки указанное клиентом', null=True, verbose_name='Доставка от')),
                ('possible_delivery_time_to', models.DateTimeField(blank=True, help_text='Желаемое время доставки указанное клиентом', null=True, verbose_name='Доставка до')),
                ('delivery_cost', base.for_model.PriceField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость доставки')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Доставлено')),
                ('delivered_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время доставки')),
                ('returned', models.CharField(blank=True, choices=[('full', 'Полный'), ('partial', 'Частичный')], editable=False, max_length=100, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.address', verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'db_table': 'Delivery',
            },
        ),
    ]
