# Generated by Django 5.0 on 2026-01-12 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='orders.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьер'), ('nova_posta', 'Nova Posta')], default='pickup', max_length=100, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='returned',
            field=models.CharField(blank=True, choices=[('full', 'Полный'), ('partial', 'Частичный')], editable=False, max_length=100, null=True, verbose_name='Возврат'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='urgency',
            field=models.CharField(choices=[('quickly', 'Срочно'), ('standard', 'Стандартно')], default='standard', max_length=100, verbose_name='Срочность'),
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='delivery',
        ),
    ]
