# Generated by Django 6.0.1 on 2026-01-13 10:44

import base.for_model
import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_historicaladdress'),
        ('delivery', '0003_remove_delivery_user_delivery_recipient_and_more'),
        ('orders', '0003_rename_user_order_customer_orderitem_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDelivery',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Обновлено')),
                ('unknown_recipient', models.TextField(blank=True, null=True, verbose_name='Неизвестный получатель')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьер'), ('nova_posta', 'Nova Posta')], default='pickup', max_length=100, verbose_name='Способ доставки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('urgency', models.CharField(choices=[('quickly', 'Срочно'), ('standard', 'Стандартно')], default='standard', max_length=100, verbose_name='Срочность')),
                ('possible_delivery_time_from', models.DateTimeField(blank=True, help_text='Желаемое время доставки указанное клиентом', null=True, verbose_name='Доставка от')),
                ('possible_delivery_time_to', models.DateTimeField(blank=True, help_text='Желаемое время доставки указанное клиентом', null=True, verbose_name='Доставка до')),
                ('delivery_cost', base.for_model.PriceField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость доставки')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Доставлено')),
                ('delivered_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время доставки')),
                ('returned', models.CharField(blank=True, choices=[('full', 'Полный'), ('partial', 'Частичный')], editable=False, max_length=100, null=True, verbose_name='Возврат')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='address.address', verbose_name='Адрес')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.order', verbose_name='Заказ')),
                ('recipient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'historical Доставка',
                'verbose_name_plural': 'historical Доставки',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
