# Generated by Django 6.0.1 on 2026-04-04 11:23

import base.for_model
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierDeliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('city', models.CharField(max_length=50)),
                ('cost', base.for_model.PriceField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'verbose_name': 'Стоимость курьерской доставки',
                'verbose_name_plural': 'Стоимость курьерской доставки',
                'db_table': 'courier_delivery_cost',
            },
        ),
    ]
