# Generated by Django 6.0.1 on 2026-01-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_historicaldelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='historicaldelivery',
            name='urgency',
        ),
        migrations.AddField(
            model_name='delivery',
            name='possible_delivery_date',
            field=models.DateField(blank=True, help_text='Желаемая дата доставки указанная клиентом', null=True, verbose_name='Желаемая дата доставки'),
        ),
        migrations.AddField(
            model_name='historicaldelivery',
            name='possible_delivery_date',
            field=models.DateField(blank=True, help_text='Желаемая дата доставки указанная клиентом', null=True, verbose_name='Желаемая дата доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='possible_delivery_time_from',
            field=models.TimeField(blank=True, help_text='Желаемое время доставки указанное клиентом', null=True, verbose_name='Доставка от'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='possible_delivery_time_to',
            field=models.TimeField(blank=True, help_text='Желаемое время доставки указанное клиентом', null=True, verbose_name='Доставка до'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='possible_delivery_time_from',
            field=models.TimeField(blank=True, help_text='Желаемое время доставки указанное клиентом', null=True, verbose_name='Доставка от'),
        ),
        migrations.AlterField(
            model_name='historicaldelivery',
            name='possible_delivery_time_to',
            field=models.TimeField(blank=True, help_text='Желаемое время доставки указанное клиентом', null=True, verbose_name='Доставка до'),
        ),
    ]
