# Generated by Django 6.0.1 on 2026-04-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_courierdeliveryprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Место самовывоза',
                'verbose_name_plural': 'Места самовывоза',
                'db_table': 'pickup_place',
            },
        ),
    ]
