# Generated by Django 6.0.1 on 2026-01-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_delivery_urgency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='unknown_recipient',
        ),
        migrations.DeleteModel(
            name='HistoricalDelivery',
        ),
    ]
