# Generated by Django 6.0.1 on 2026-04-04 12:21

import base.for_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_pickupplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierdeliveryprice',
            name='position',
            field=base.for_model.PositionField(default=0, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='pickupplace',
            name='position',
            field=base.for_model.PositionField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='courierdeliveryprice',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='pickupplace',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
    ]
