# Generated by Django 6.0.1 on 2026-04-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_courierdeliveryprice_position_pickupplace_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierdeliveryprice',
            name='city',
            field=models.CharField(max_length=50, unique=True, verbose_name='Населенный пункт'),
        ),
    ]
