# Generated by Django 6.0.1 on 2026-01-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remove_delivery_unknown_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='possible_delivery_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='possible_delivery_time_from',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='possible_delivery_time_to',
        ),
    ]
