# Generated by Django 6.0.1 on 2026-05-20 15:02

import apps.delivery.models.pickup_place
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_courierdeliveryprice_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.delivery.models.pickup_place.get_upload_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='pickupplace',
            name='show_room',
            field=models.BooleanField(default=False, verbose_name='Show Room'),
        ),
    ]
