# Generated by Django 6.0.1 on 2026-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_remove_delivery_possible_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='post_office',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер почтового отделения | почтомата'),
        ),
    ]
