# Generated by Django 6.0.1 on 2026-06-07 13:19

import base.for_model
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('delivery', '0008_pickupplace_image_pickupplace_show_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='post_office',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='address',
        ),
        migrations.CreateModel(
            name='PickUpDelivery',
            fields=[
                ('delivery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delivery.delivery')),
            ],
            options={
                'verbose_name': 'Доставка [Самовывоз]',
                'verbose_name_plural': 'Доставки [Самовывоз]',
                'db_table': 'delivery_pickup',
            },
            bases=('delivery.delivery',),
        ),
        migrations.DeleteModel(
            name='CourierDeliveryPrice',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('nova_posta', 'Nova Posta')], max_length=100, verbose_name='Способ доставки'),
        ),
        migrations.CreateModel(
            name='NovaPostaDelivery',
            fields=[
                ('delivery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delivery.delivery')),
                ('post_office', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер почтового отделения')),
                ('parcel_locker', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер  почтомата')),
                ('delivery_cost', base.for_model.PriceField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость доставки')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Доставка [Nova Posta]',
                'verbose_name_plural': 'Доставки [Nova Posta]',
                'db_table': 'delivery_nova_posta',
            },
            bases=('delivery.delivery',),
        ),
    ]
