# Generated by Django 6.0.1 on 2026-06-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_remove_delivery_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupdelivery',
            name='pickup_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.pickupplace', verbose_name='Pickup Place'),
        ),
    ]
