# Generated by Django 6.0.1 on 2026-04-01 15:03

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import base.for_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "status",
                    models.CharField(
                        choices=[("cart", "Корзина"), ("order", "Заказ")],
                        default="cart",
                        max_length=100,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "price",
                    base.for_model.PriceField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Цена продажи",
                    ),
                ),
                (
                    "discount",
                    base.for_model.PriceField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Скидка",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Название товара"
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав заказа",
                "verbose_name_plural": "Состав заказа",
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "В процессе"),
                            ("paid", "Оплачен"),
                            ("cancelled", "Отменен"),
                            ("FAIL", "Провален"),
                            ("REFUND", "Отменен"),
                            ("PARTIAL_REFUND", "Частично отменен"),
                        ],
                        default="IN_PROGRESS",
                        max_length=100,
                        verbose_name="Статус платежа",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Наличная"), ("cashless", "Безналичная")],
                        default="cash",
                        max_length=100,
                        verbose_name="Метод оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата заказа",
                "verbose_name_plural": "Оплата заказов",
                "db_table": "order_payment",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "id",
                    models.CharField(
                        default=base.for_model.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_work", "В работе"),
                            ("completed", "Выполнен"),
                        ],
                        default="draft",
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "total_price",
                    base.for_model.PriceField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Общая цена",
                    ),
                ),
                (
                    "total_discount",
                    base.for_model.PriceField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Общая скидка",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Комментарий к заказу"
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(blank=True, null=True, verbose_name="Additional Data"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sessions.session",
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "orders",
            },
        ),
    ]
