# Generated by Django 6.0.1 on 2026-04-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('paid', 'Оплачен'), ('cancelled', 'Отменен'), ('fail', 'Провален'), ('refund', 'Отменен'), ('partial_refund', 'Частично отменен')], default='in_progress', max_length=100, verbose_name='Статус платежа'),
        ),
    ]
