# Generated by Django 6.0.1 on 2026-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderpayment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='session',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Сессия'),
        ),
    ]
