# Generated by Django 6.0.1 on 2026-01-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
