# Generated by Django 6.0.1 on 2026-01-25 20:21

import base.for_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_customer_historicalorder_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorderitem',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='historicalorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalorderitem',
            name='session',
        ),
        migrations.RemoveField(
            model_name='historicalorderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalorderpayment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorderpayment',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=base.for_model.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('cart', 'Корзина'), ('order', 'Заказ')], default='cart', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличная'), ('cashless', 'Безналичная')], default='cash', max_length=100, verbose_name='Метод оплаты'),
        ),
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
        migrations.DeleteModel(
            name='HistoricalOrderItem',
        ),
        migrations.DeleteModel(
            name='HistoricalOrderPayment',
        ),
    ]
