# Generated by Django 5.0 on 2025-12-09 20:47

import base.for_model
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='ProductSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_price', base.for_model.PriceField(blank=True, decimal_places=2, help_text='Заполнять не нужно. Пересчитается автоматически по курсу', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Закупочная цена [MLD]')),
                ('purchase_price_usd', base.for_model.PriceField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Закупочная цена [USD]')),
                ('qty', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_through', to='products.product')),
            ],
            options={
                'verbose_name': 'Товар в партии',
                'verbose_name_plural': 'Товары в партии',
                'db_table': 'product_supply_m2m',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_batch_paid', models.BooleanField(default=False, verbose_name='Товар оплачен')),
                ('import_coast', base.for_model.PriceField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость растаможки')),
                ('is_import_paid', models.BooleanField(default=False, verbose_name='Растаможка оплачена')),
                ('sent_at', models.DateField(verbose_name='Дата отправки')),
                ('received_at', models.DateField(verbose_name='Дата получения')),
                ('products', models.ManyToManyField(through='supply.ProductSupply', to='products.product', verbose_name='Товары')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply', to='supply.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Партия товара',
                'verbose_name_plural': 'Партии товаров',
                'db_table': 'supply',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.AddField(
            model_name='productsupply',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_through', to='supply.supply'),
        ),
    ]
