# Generated by Django 5.0 on 2025-12-09 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_is_active'),
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupply',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_through', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productsupply',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_through', to='supply.supply', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='received_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='sent_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
