# Generated by Django 6.0.1 on 2026-01-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_historicalproductsupply_historicalsupplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsupplier',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsupply',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsupply',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='HistoricalProductSupply',
        ),
        migrations.DeleteModel(
            name='HistoricalSupplier',
        ),
        migrations.DeleteModel(
            name='HistoricalSupply',
        ),
    ]
