# Generated by Django 6.0.1 on 2026-05-20 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0008_pickupplace_image_pickupplace_show_room'),
        ('products', '0006_product_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата примерки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланировано'), ('canceled', 'Отменён'), ('held', 'Состоялась')], default='draft', max_length=100, verbose_name='Статус')),
                ('products', models.ManyToManyField(blank=True, related_name='fittings', to='products.product', verbose_name='Товар')),
                ('show_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.pickupplace', verbose_name='Show Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Примерка',
                'verbose_name_plural': 'Примерки',
                'db_table': 'fittings',
                'ordering': ('-date',),
            },
        ),
    ]
