# Generated by Django 6.0.1 on 2026-06-07 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_remove_delivery_delivery_cost_and_more'),
        ('fitting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fitting',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='fitting',
            name='show_room',
            field=models.ForeignKey(blank=True, limit_choices_to={'show_room': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.pickupplace', verbose_name='Show Room'),
        ),
        migrations.AlterField(
            model_name='fitting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fittings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
