# Generated by Django 6.0.1 on 2026-06-07 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0002_fitting_session_key_alter_fitting_show_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fittings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
