[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:gunicorn]
command=gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 1 --timeout 120
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:tg-bot]
command=python manage.py run_tg_bot
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
