# Generated by Django 6.0.1 on 2026-04-01 15:03

import django.contrib.auth.validators
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("address", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without "
                                  "explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        error_messages={
                            "unique": "Пользователь с таким иднтификатором уже существует."
                        },
                        help_text="Используется для входа (email или телефон)",
                        max_length=150,
                        null=True,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="Идетификатор пользователя",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="Фамилия"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Телеграм ID"
                    ),
                ),
                (
                    "staff_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("owner", "Владелец"),
                            ("developer", "Разработчик"),
                            ("delivery_man", "Доставщик"),
                            ("sales_man", "Продавец"),
                            ("booker", "Бухгалтер"),
                            ("manager", "Менеджер"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Статус",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="Статус персонала")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активный")),
                ("is_baned", models.BooleanField(default=False, verbose_name="Забанен")),
                (
                    "addresses",
                    models.ManyToManyField(blank=True, to="address.address", verbose_name="Адреса"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "user",
            },
        ),
    ]
