# Generated by Django 6.0.1 on 2026-04-01 19:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionChat',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('action_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('new_order', 'Новый заказ'), ('new_customer', 'Новый клиент'), ('errors', 'Ошибки')], max_length=50), blank=True, default=list, verbose_name='Подписки на события')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_chats', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Telegram чат',
                'verbose_name_plural': 'Telegram чаты',
            },
        ),
    ]
