# Generated by Django 5.0 on 2025-12-09 20:47

import django_google_maps.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', django_google_maps.fields.AddressField(max_length=200, verbose_name='Адрес')),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100, verbose_name='Геолокация')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'address',
            },
        ),
    ]
