# Generated by Django 6.0.1 on 2026-01-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_historicaladdress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalAddress',
        ),
    ]
